gui:
  sidePanelWidth: 0.25 # gives you more space to show things side-by-side
  nerdFontsVersion: ""

git:
  paging:
    colorArg: never
    pager: ydiff -p cat -s --wrap --width={{columnWidth}}
    # pager: delta --show-syntax-themes --dark
