# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true
after-startup-command = [
  # 'exec-and-forget borders active_color=0xff85929e inactive_color=0xff494d64 width=4.0 hidpi=on'
]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 50

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
automatically-unhide-macos-hidden-apps = true

[exec]
    inherit-env-vars = true

[exec.env-vars]
    PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    # Launch apps
    cmd-t = 'exec-and-forget open -n /Applications/kitty.app'
    cmd-b = '''exec-and-forget open -n /Applications/'Google Chrome.app''''
    # TODO: Improve finder
    cmd-n = 'exec-and-forget open ~'
    cmd-a = 'exec-and-forget open -n /System/Applications/Launchpad.app'
    cmd-m = '''exec-and-forget open -n /System/Applications/'System Settings.app''''

    cmd-s = 'exec-and-forget aerospace list-windows --all --format "%{workspace}%{right-padding} | %{app-name}%{right-padding}  (%{window-id})" | choose | cut -d"(" -f2 | cut -d")" -f1 | xargs -I {} aerospace focus --window-id {}'
    cmd-d = 'exec-and-forget aerospace list-windows --workspace focused --format "%{workspace}%{right-padding} | %{app-name}%{right-padding}  (%{window-id})" | choose | cut -d"(" -f2 | cut -d")" -f1 | xargs -I {} aerospace focus --window-id {}'

    # TODO: Screenshot bindings
    # cmd-p = '''exec-and-forget screencapture ~/Pictures/test.jpg''''

    # Close app
    cmd-shift-q = 'close'

    cmd-h = 'focus left'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-l = 'focus right'

    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    cmd-ctrl-h = 'split horizontal'
    cmd-ctrl-v = 'split vertical'

    cmd-space = 'fullscreen --no-outer-gaps'
    # cmd-space = 'macos-native-fullscreen'  # clunky

    # cmd-s = 'layout v_accordion' # 'layout stacking' in i3
    cmd-w = 'layout h_accordion' # 'layout tabbed' in i3
    cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    cmd-shift-f = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #cmd-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # cmd-a = 'focus parent'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    cmd-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    cmd-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    cmd-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    cmd-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    cmd-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
    cmd-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
    cmd-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
    cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
    cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
    cmd-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'

    cmd-shift-c = 'reload-config'

    cmd-r = 'mode resize'

[workspace-to-monitor-force-assignment]
    1 = 'secondary'                  # Non-main monitor in case when there are only two monitors
    2 = 'secondary'                  
    3 = 'secondary'                 
    4 = 'secondary'                  
    5 = 'secondary'                
    6 = 'main'
    7 = 'main'
    8 = 'main'
    9 = 'main'
    10 = 'main'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

