local set = vim.opt

-- set.nocompatible = true           -- disable compatibility to old-time vi
-- set.showmatch = true               -- show matching
set.ignorecase = true             -- case insensitive
set.hlsearch = true                -- highlight search
set.incsearch = true               -- incremental search
set.tabstop = 4               -- number of columns occupied by a tab
set.softtabstop = 4           -- see multiple spaces as tabstops so <BS> does the right thing
set.expandtab = true               -- converts tabs to white space
set.shiftwidth = 4            -- width for autoindents
set.autoindent = true             -- indent a new line the same amount as the line just typed
set.number = true                 -- add line numbers
set.relativenumber = true 	-- add relative line numbers
-- set.wildmode=longest,list   -- get bash-like tab completions
-- set.cc = 120                  -- set an 80 column border for good coding style
-- set.mouse = v                 -- middle-click paste with
set.mouse = 'a'                 -- enable mouse click
set.clipboard=unnamedplus   -- using system clipboard
set.cursorline = true             -- highlight current cursorline
set.ttyfast = true                 -- Speed up scrolling in Vim
set.termguicolors = true 
set.scrolloff = 5
set.updatetime =10
