# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true
after-startup-command = [
  # 'exec-and-forget borders active_color=0xff85929e inactive_color=0xff494d64 width=4.0 hidpi=on'
]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 50

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
automatically-unhide-macos-hidden-apps = true

[exec]
    inherit-env-vars = true

[exec.env-vars]
    PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    # Mode switch
    alt-ctrl-cmd-r = 'mode resize'
    alt-ctrl-cmd-p = 'mode personal'

    # Launch apps
    alt-ctrl-cmd-t = 'exec-and-forget open -n /Applications/kitty.app'
    alt-ctrl-cmd-b = '''exec-and-forget open -n /Applications/'Google Chrome.app''''
    # TODO: Improve finder
    alt-ctrl-cmd-n = 'exec-and-forget open ~'
    alt-ctrl-cmd-a = 'exec-and-forget open -n /System/Applications/Launchpad.app'
    alt-ctrl-cmd-m = '''exec-and-forget open -n /System/Applications/'System Settings.app''''

    alt-ctrl-cmd-s = 'exec-and-forget aerospace list-windows --all --format "%{workspace}%{right-padding} | %{app-name}%{right-padding}  (%{window-id})" | choose | cut -d"(" -f2 | cut -d")" -f1 | xargs -I {} aerospace focus --window-id {}'
    alt-ctrl-cmd-d = 'exec-and-forget aerospace list-windows --workspace focused --format "%{workspace}%{right-padding} | %{app-name}%{right-padding}  (%{window-id})" | choose | cut -d"(" -f2 | cut -d")" -f1 | xargs -I {} aerospace focus --window-id {}'

    # TODO: Screenshot bindings
    # alt-ctrl-cmd-p = '''exec-and-forget screencapture ~/Pictures/test.jpg''''

    # Close app
    alt-ctrl-cmd-shift-q = 'close --quit-if-last-window'

    alt-ctrl-cmd-h = 'focus left'
    alt-ctrl-cmd-j = 'focus down'
    alt-ctrl-cmd-k = 'focus up'
    alt-ctrl-cmd-l = 'focus right'

    alt-ctrl-cmd-shift-h = 'move left'
    alt-ctrl-cmd-shift-j = 'move down'
    alt-ctrl-cmd-shift-k = 'move up'
    alt-ctrl-cmd-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    # cmd-ctrl-h = 'split horizontal'
    # cmd-ctrl-v = 'split vertical'

    alt-ctrl-cmd-space = 'fullscreen --no-outer-gaps'
    # alt-ctrl-cmd-space = 'macos-native-fullscreen'  # clunky

    # alt-ctrl-cmd-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-ctrl-cmd-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-ctrl-cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-ctrl-cmd-shift-f = 'layout floating tiling' # 'floating toggle' in i3

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-ctrl-cmd-a = 'focus parent'

    alt-ctrl-cmd-shift-c = 'reload-config'

    alt-ctrl-cmd-1 = 'workspace 1'
    alt-ctrl-cmd-2 = 'workspace 2'
    alt-ctrl-cmd-3 = 'workspace 3'
    alt-ctrl-cmd-4 = 'workspace 4'
    alt-ctrl-cmd-5 = 'workspace 5'
    alt-ctrl-cmd-6 = 'workspace 6'
    alt-ctrl-cmd-7 = 'workspace 7'
    alt-ctrl-cmd-8 = 'workspace 8'
    alt-ctrl-cmd-9 = 'workspace 9'
    alt-ctrl-cmd-0 = 'workspace 10'

    alt-ctrl-cmd-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    alt-ctrl-cmd-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    alt-ctrl-cmd-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    alt-ctrl-cmd-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    alt-ctrl-cmd-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
    alt-ctrl-cmd-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
    alt-ctrl-cmd-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
    alt-ctrl-cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
    alt-ctrl-cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
    alt-ctrl-cmd-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'

[mode.personal.binding]
    # Mode switch
    alt-ctrl-cmd-r = 'mode resize'
    alt-ctrl-cmd-p = 'mode main'

    # Launch apps
    alt-ctrl-cmd-t = 'exec-and-forget open -n /Applications/kitty.app'
    alt-ctrl-cmd-b = '''exec-and-forget open -n /Applications/'Google Chrome.app''''
    # TODO: Improve finder
    alt-ctrl-cmd-n = 'exec-and-forget open ~'
    alt-ctrl-cmd-a = 'exec-and-forget open -n /System/Applications/Launchpad.app'
    alt-ctrl-cmd-m = '''exec-and-forget open -n /System/Applications/'System Settings.app''''

    alt-ctrl-cmd-s = 'exec-and-forget aerospace list-windows --all --format "%{workspace}%{right-padding} | %{app-name}%{right-padding}  (%{window-id})" | choose | cut -d"(" -f2 | cut -d")" -f1 | xargs -I {} aerospace focus --window-id {}'
    alt-ctrl-cmd-d = 'exec-and-forget aerospace list-windows --workspace focused --format "%{workspace}%{right-padding} | %{app-name}%{right-padding}  (%{window-id})" | choose | cut -d"(" -f2 | cut -d")" -f1 | xargs -I {} aerospace focus --window-id {}'

    # TODO: Screenshot bindings
    # alt-ctrl-cmd-p = '''exec-and-forget screencapture ~/Pictures/test.jpg''''

    # Close app
    alt-ctrl-cmd-shift-q = 'close --quit-if-last-window'

    alt-ctrl-cmd-h = 'focus left'
    alt-ctrl-cmd-j = 'focus down'
    alt-ctrl-cmd-k = 'focus up'
    alt-ctrl-cmd-l = 'focus right'

    alt-ctrl-cmd-shift-h = 'move left'
    alt-ctrl-cmd-shift-j = 'move down'
    alt-ctrl-cmd-shift-k = 'move up'
    alt-ctrl-cmd-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    # cmd-ctrl-h = 'split horizontal'
    # cmd-ctrl-v = 'split vertical'

    alt-ctrl-cmd-space = 'fullscreen --no-outer-gaps'
    # alt-ctrl-cmd-space = 'macos-native-fullscreen'  # clunky

    # alt-ctrl-cmd-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-ctrl-cmd-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-ctrl-cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-ctrl-cmd-shift-f = 'layout floating tiling' # 'floating toggle' in i3

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-ctrl-cmd-a = 'focus parent'

    alt-ctrl-cmd-shift-c = 'reload-config'

    alt-ctrl-cmd-1 = 'workspace 11'
    alt-ctrl-cmd-2 = 'workspace 12'
    alt-ctrl-cmd-3 = 'workspace 13'
    alt-ctrl-cmd-4 = 'workspace 14'
    alt-ctrl-cmd-5 = 'workspace 15'
    alt-ctrl-cmd-6 = 'workspace 16'
    alt-ctrl-cmd-7 = 'workspace 17'
    alt-ctrl-cmd-8 = 'workspace 8'
    alt-ctrl-cmd-9 = 'workspace 9'
    alt-ctrl-cmd-0 = 'workspace 10'

    alt-ctrl-cmd-shift-1 = 'move-node-to-workspace 11 --focus-follows-window'
    alt-ctrl-cmd-shift-2 = 'move-node-to-workspace 12 --focus-follows-window'
    alt-ctrl-cmd-shift-3 = 'move-node-to-workspace 13 --focus-follows-window'
    alt-ctrl-cmd-shift-4 = 'move-node-to-workspace 14 --focus-follows-window'
    alt-ctrl-cmd-shift-5 = 'move-node-to-workspace 15 --focus-follows-window'
    alt-ctrl-cmd-shift-6 = 'move-node-to-workspace 16 --focus-follows-window'
    alt-ctrl-cmd-shift-7 = 'move-node-to-workspace 17 --focus-follows-window'
    alt-ctrl-cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
    alt-ctrl-cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
    alt-ctrl-cmd-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'


[workspace-to-monitor-force-assignment]
    # Non-main monitor in case when there are only two monitors
    1 = 'main'                  
    2 = 'main'                  
    3 = 'main'                 
    4 = 'main'                  
    5 = 'main'                
    6 = 'main'
    7 = 'main'
    8 = 'main'
    9 = 'main'
    10 = 'main'
    11 = 'main'                  
    12 = 'main'                  
    13 = 'main'                 
    14 = 'main'                  
    15 = 'main'                
    16 = 'main'
    17 = 'main'
    18 = 'main'
    19 = 'main'
    20 = 'main'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

